### ISSUE TITLE
Inserted code is platform dependent

### ISSUE THREAD

**Issue by aecz** [yeoman/html-wiring#2]
https://github.com/yeoman/html-wiring/blob/master/index.js#L164

``` javascript
files += wiring.appendIndent('<script ' + attrs + ' src="' + el + '"></script>\n');
```

The above code is an example where the character **\n** is inserted.

This **breaks the compatibility** with platforms using a different **EOL character** than \n.

Variable **os.EOL** from NodeJS API could be used as it is **platform independent**.

This seems also related to this issue: https://github.com/yeoman/generator/issues/370

I would be glad to submit a **pull request** if asked.

**Comment by sindresorhus** [comment]
:-1: Just use `\n`. Any editor supports that.

**Comment by arthurvr** [comment]
> :-1: Just use \n. Any editor supports that.

Yup, that's my feeling as well.

**Comment by arthurvr** [comment]
ping? I personally think it's quite clear that people should just use `\n`, honestly.

**Comment by SBoudrias** [comment]
I actually believe using platform EOL would make sense. It's more verbose and annoying, but it ensure support and it ensure you won't end up with mixed EOL in your files.

Having worked in windows for a while, I know it's not as easy as only using ln and having an editor who supports it. It always create issues with git normalization flow, etc.

A PR is welcomed.

**Comment by passy** [comment]
I thought most people would normalize their line endings to normal unix (`\n`) these days anyway. I have a global git setting to do that.

**Comment by SBoudrias** [comment]
@passy pretty sure Git only normalize when pushing, it'll still checkout the native line ending for the platform. - At least it was this way when I worked on Windows.

**Comment by aecz** [comment]
I repeat myself that i think it is about writing **platform-independent** code.
If we force the insert of "\n", it is like forcing yeoman to only work flawlessly on Unix and not caring about non-Unix users.

I still do not see a reason for NOT using **os.EOL** so why not welcoming a PR like @SBoudrias ?

Also when a Yeoman generator is installed on Windows, the downloaded files are unzipped and converted to Windows EOL. This does not depend on your Git nor on your editor configuration.

**Comment by sindresorhus** [comment]
> If we force the insert of "\n", it is like forcing yeoman to only work flawlessly on Unix and not caring about non-Unix users.

No, it's like forcing consistency. Windows supports `\n` fine.

**Comment by aecz** [comment]
Then Yeoman code is inconsistent with NodeJS API and NPM code which are using os.EOL:
https://github.com/npm/npm/blob/064d62c2f251cb5e9328f63228f711844b7a1787/lib/config.js#L100
Yeoman does not play well with NPM as i stated in my previous comment and that affects non-Unix users. I suggest we make Yeoman friendly to use for all users.
Previous comments are only a workaround given to users to make it work but it should work out-of-the-box in my opinion.
I still do not see a reason to not make this change. Why not accept it ? Any example or use case ?
Another option could be to check which EOL is used in the file and insert the same EOL.
What do you think of that other option ?

**Comment by robbbz** [comment]
We shouldn't deal with what the platform screws up and people that are willing to use that OS should normalize themselves.

@SBoudrias Git normalizes on commit, not on push.

> No, it's like forcing consistency. Windows supports `\n` fine.

+1.

**Comment by SBoudrias** [comment]
> We shouldn't deal with what the platform screws up and people that are willing to use that OS should normalize themselves.

This is a very limited view. Not every people programming are rich people able to afford Macbook. People program all over the world with a lot of different system and they're all allowed to do so with the tools they want.

Windows support is a priority for the Yeoman team and our tools should work seamlessly between platforms.

---

So the correct fix here is in two way:
1. We need to detect which line ending is used in the written file.
2. We need to use that line ending.

A correct PR fixing this issue will be merged.

**Comment by aecz** [comment]
I submitted a PR: https://github.com/yeoman/html-wiring/pull/3

**Comment by sindresorhus** [comment]
> This is a very limited view. Not every people programming are rich people able to afford Macbook.

Ironically this is too, as `\n` primarily comes from Unix, which runs on most hardware in existence :p

> So the correct fix here is in two way:

I'm fine with that.
