### ISSUE TITLE
Can we have some docs please?

### ISSUE THREAD

**Issue by mrsimonemms** [yeoman/html-wiring#4]
I've seen various blog posts that the `this.readFileAsString` and `this.writeFileAsString` methods are being deprecated in favour of this package.

Can we have some docs on how to use this please?

**Comment by arthurvr** [comment]
For now please look at the documentation comments in the code.

Although, yeah, let's move it to the readme?

**Comment by mrsimonemms** [comment]
I've looked the comments in the code and it's not very thorough - 1 or 2 lines at most.  It's probably ok for those who wrote and know roughly how it works, but I'm coming into completely cold. I also don't know which methods I ought to be looking at.

Also, some examples would be useful.

**Comment by SBoudrias** [comment]
This package have mostly been done for backward compatibility. I don't think you should use it for any new project.

**Comment by sindresorhus** [comment]
> This package have mostly been done for backward compatibility. I don't think you should use it for any new project.

The readme should be clear about that.

**Comment by mrsimonemms** [comment]
I've seen a few posts (such as [this one](http://stackoverflow.com/questions/19178523/can-yeoman-generators-update-existing-files) by ivoba) that says the yeoman wiring is being deprecated in favour of this package.

Is that not that case then?

**Comment by SBoudrias** [comment]
@riggerthegeek Yeoman wiring is removed from the core and extracted to this package. This is an almost verbatim version of what was in the core before.

If you're interested in maintaining the package and doing something great with it, then go forward. But I don't think anyone on the core team is presently interested in maintaining this package further than its current state.

**Comment by sindresorhus** [comment]
Closing as this package is deprecated.
